### ISSUE TITLE
Secret ApiKey

### ISSUE THREAD

**Issue by AmeerMansourBeca** [unifilabs/UNIFI-ContentManagement-API-Sample#10]
how ApiKey value should be in Secrets.cs?

**Comment by jmerlan** [comment]
Simply replace the string in [line 3](https://github.com/unifilabs/UNIFI-ContentManagement-API-Sample/blob/977d6c81feee64c2a44ae513ae101baf3d2d47f2/Samples.ContentManagement/Secrets.cs#L3).

**Comment by AmeerMansourBeca** [comment]
@jmerlan 
yes but how can i get it?

**Comment by jmerlan** [comment]
You need to request one from support@unifilabs.com.

**Comment by AmeerMansourBeca** [comment]
thanks
i sent them mail.
